-- Creates a sample database for the demo. This script was generated from Sql Server 2019 Developer Edition using SSMS.
-- It creates a 'JsonTest' database with two tables and a view. Once this is done the 'SampleData.sql' script will populate a single
-- row into the database

USE [master]
GO
/****** Object:  Database [JsonTest]    Script Date: 01/05/2020 13:20:42 ******/
CREATE DATABASE [JsonTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JsonTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019DEV\MSSQL\DATA\JsonTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JsonTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019DEV\MSSQL\DATA\JsonTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [JsonTest] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JsonTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JsonTest] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JsonTest] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JsonTest] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JsonTest] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JsonTest] SET ARITHABORT OFF 
GO
ALTER DATABASE [JsonTest] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [JsonTest] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JsonTest] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JsonTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JsonTest] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JsonTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JsonTest] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JsonTest] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JsonTest] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JsonTest] SET  DISABLE_BROKER 
GO
ALTER DATABASE [JsonTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JsonTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JsonTest] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JsonTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JsonTest] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JsonTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JsonTest] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JsonTest] SET RECOVERY FULL 
GO
ALTER DATABASE [JsonTest] SET  MULTI_USER 
GO
ALTER DATABASE [JsonTest] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JsonTest] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JsonTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JsonTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [JsonTest] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'JsonTest', N'ON'
GO
ALTER DATABASE [JsonTest] SET QUERY_STORE = OFF
GO
USE [JsonTest]
GO
/****** Object:  Table [dbo].[People]    Script Date: 01/05/2020 13:20:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[People](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](512) NOT NULL,
 CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Addresses]    Script Date: 01/05/2020 13:20:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Addresses](
	[Id] [uniqueidentifier] NOT NULL,
	[PeopleId] [uniqueidentifier] NOT NULL,
	[Line1] [nvarchar](512) NOT NULL,
	[Line2] [nvarchar](512) NOT NULL,
 CONSTRAINT [PK_Addresses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[RawAddressView]    Script Date: 01/05/2020 13:20:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[RawAddressView]
AS
	select
		People.Name as [name],
		Addresses.Line1 as [address_line1],
		Addresses.Line2 as [address_line2]
	from
		People
	inner join
		Addresses
	on
		Addresses.PeopleId = People.Id
GO
/****** Object:  Index [IX_Addresses]    Script Date: 01/05/2020 13:20:43 ******/
CREATE NONCLUSTERED INDEX [IX_Addresses] ON [dbo].[Addresses]
(
	[PeopleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Addresses]  WITH CHECK ADD  CONSTRAINT [FK_Addresses_People] FOREIGN KEY([PeopleId])
REFERENCES [dbo].[People] ([Id])
GO
ALTER TABLE [dbo].[Addresses] CHECK CONSTRAINT [FK_Addresses_People]
GO
USE [master]
GO
ALTER DATABASE [JsonTest] SET  READ_WRITE 
GO
